name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          release-type: simple
      - name: Debug release-please output
        env:
          RELEASE_PLEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: |
          echo "Debug: print release-please output"
          echo "$RELEASE_PLEASE_OUTPUTS"

  debug:
    name: Debug
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Debug:"
          echo "Release created: ${{ needs.release.outputs.releases_created }}"
          echo "Tag name: ${{ needs.release.outputs.tag_name }}"
          echo "Version: ${{ needs.release.outputs.version }}"

  publish:
    name: Publish
    needs: release
    if: needs.release.outputs.releases_created == "true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release ${{ needs.release.outputs.tag_name }}
        uses: actions/checkout@v7
        with:
          ref: '${{ needs.release.outputs.tag_name }}'
      - run: |
          ls -lah
          git status
