name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
      - name: Debug release-please output
        env:
          RELEASE_PLEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: |
          echo "Debug: print release-please output"
          echo "$RELEASE_PLEASE_OUTPUTS"

  publish:
    name: Publish
    needs: release
    if: needs.release.releases_created == "true"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Print release please output"
          echo "Publish:"
          echo "Tag name: ${{ needs.release.tag_name }}"
          echo "Version: ${{ needs.release.version }}"
